name: 🍫 Validate Choco

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - uses: actions/checkout@v4
      # Run the shared workflow
      - uses: TheChocolateyFactory/.github/shared-workflow/ChocoValidate.yml@main
