name: 🍫 Validate Choco

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  # Run the shared workflow
  shared:
    uses: TheChocolateyFactory/.github/.github/workflows/ChocoValidate.yml@main
    with:
      nuspec_path: ./path/to/your/package.nuspec
