name: Validate Chocolatey Package
on:
  workflow_call:
    inputs:
      nuspec_path:
        description: "Path to the Chocolatey nuspec to build and validate"
        required: true
        type: string

jobs:
  work:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout .github repo
        uses: actions/checkout@v4
        with:
          repository: TheChocolateyFactory/.github
          path: ./dot_github/
          ref: main

      - name: Test nuspec
        shell: pwsh
        run: |
          Import-Module -Name 'Pester' -MinimumVersion 5.3.0
          $configuration = [PesterConfiguration]::Default
          $configuration.Run.Container = New-PesterContainer -Path .\dot_github\tests\nuspec_required.tests.ps1 -Data @{NuspecPath='${{ inputs.nuspec_path }}'}
          Invoke-Pester -Configuration $configuration

      - name: Build Chocolatey Package
        shell: pwsh
        run: |
          $packagePath = '${{ inputs.package_path }}'
          if (-not (Test-Path $packagePath)) {
            Write-Error "Package path '$packagePath' does not exist."
          }
          choco pack $packagePath --outputdirectory ./output

      - name: Validate Chocolatey Package
        shell: pwsh
        run: |
          $nupkgPath = Get-ChildItem './output/*.nupkg'
          if (-not (Test-Path $nupkgPath)) {
            Write-Error "No nupkg found in output directory."
          }
          Import-Module -Name 'Pester' -MinimumVersion 5.3.0
          $configuration = [PesterConfiguration]::Default
          $configuration.Run.Container = New-PesterContainer -Path .\dot_github\tests\package_required.tests.ps1 -Data @{PackagePath=$nupkgPath.FullName}
          Invoke-Pester -Configuration $configuration
